

import type React from "react";
import { Header } from "@/components/header";
import { Sidebar } from "@/components/sidebar";
import "../globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Metadata } from "next";
import Providers from "@/Providers/Providers";
import { Toaster } from "sonner";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Veloo Service Provider Dashboard",
  description: "Generated by create next app",
};


export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={plusJakarta.variable}>
      <body className="antialiased">
        <Providers>
          <div className="flex min-h-screen gap-8 bg-[#ECFDF5]">
            {/* Sidebar */}
            <div className="lg:w-64 h-screen fixed left-0 top-0">
              <Sidebar />
            </div>

            <div className="lg:ml-72 flex-1 flex-grow">
              {/* Header */}
              <Header title="Dashboard" subtitle="Welcome back, Sharon" />

              {/* Main Content */}
              <main className="p-6 overflow-auto ">{children}</main>
              <Toaster />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
