'use client';
// import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/footer";
import CookieConsentModal from "@/components/cookie-consent-modal";
import { Toaster } from "sonner";
import Providers from "@/Providers/Providers";
import { msalInstance } from "@/components/authModal/msalConfig";
import { MsalProvider } from "@azure/msal-react";


const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Veloo Service Provider",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={plusJakarta.variable}>
      <body className="antialiased">
        <Providers>
          <MsalProvider instance={msalInstance}>
            <CookieConsentModal />
            <Navbar />

            {children}

            <Footer />
            <Toaster />
          </MsalProvider>
        </Providers>
      </body>
    </html>
  );
}
